version: '2.1'
services:
  postgres:
    image: postgres:15.1
    restart: unless-stopped
    command: ["postgres", "-c", "wal_level=logical"]
    environment:
    - POSTGRES_USER=vierkantle
    - POSTGRES_DB=vierkantle
    - POSTGRES_PASSWORD=vierkantle
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - "5433:5432"

volumes:
  db-data:
