// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package gendb

import (
	"time"
)

type VierkantleScore struct {
	BoardName   string
	AnonymousID int64
	TeamSize    int32
	Words       int32
	Seconds     int32
	StartedAt   time.Time
	UpdatedAt   time.Time
}
