// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: vierkantle.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBoardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Timezone offset in client's local time, as in Javascript Date.getTimezoneOffset()
	TimezoneOffsetMinutes int32 `protobuf:"varint,1,opt,name=timezoneOffsetMinutes,proto3" json:"timezoneOffsetMinutes,omitempty"`
}

func (x *GetBoardRequest) Reset() {
	*x = GetBoardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardRequest) ProtoMessage() {}

func (x *GetBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardRequest.ProtoReflect.Descriptor instead.
func (*GetBoardRequest) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{0}
}

func (x *GetBoardRequest) GetTimezoneOffsetMinutes() int32 {
	if x != nil {
		return x.TimezoneOffsetMinutes
	}
	return 0
}

type GetBoardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Board []byte `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetBoardResponse) Reset() {
	*x = GetBoardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardResponse) ProtoMessage() {}

func (x *GetBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardResponse.ProtoReflect.Descriptor instead.
func (*GetBoardResponse) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{1}
}

func (x *GetBoardResponse) GetBoard() []byte {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *GetBoardResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SubmitScoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnonymousId int32  `protobuf:"varint,1,opt,name=anonymous_id,json=anonymousId,proto3" json:"anonymous_id,omitempty"`
	TeamSize    int32  `protobuf:"varint,2,opt,name=team_size,json=teamSize,proto3" json:"team_size,omitempty"`
	Words       int32  `protobuf:"varint,3,opt,name=words,proto3" json:"words,omitempty"`
	Seconds     int32  `protobuf:"varint,4,opt,name=seconds,proto3" json:"seconds,omitempty"`
	BoardName   string `protobuf:"bytes,5,opt,name=boardName,proto3" json:"boardName,omitempty"`
}

func (x *SubmitScoreRequest) Reset() {
	*x = SubmitScoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitScoreRequest) ProtoMessage() {}

func (x *SubmitScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitScoreRequest.ProtoReflect.Descriptor instead.
func (*SubmitScoreRequest) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitScoreRequest) GetAnonymousId() int32 {
	if x != nil {
		return x.AnonymousId
	}
	return 0
}

func (x *SubmitScoreRequest) GetTeamSize() int32 {
	if x != nil {
		return x.TeamSize
	}
	return 0
}

func (x *SubmitScoreRequest) GetWords() int32 {
	if x != nil {
		return x.Words
	}
	return 0
}

func (x *SubmitScoreRequest) GetSeconds() int32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *SubmitScoreRequest) GetBoardName() string {
	if x != nil {
		return x.BoardName
	}
	return ""
}

type SubmitScoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubmitScoreResponse) Reset() {
	*x = SubmitScoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitScoreResponse) ProtoMessage() {}

func (x *SubmitScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitScoreResponse.ProtoReflect.Descriptor instead.
func (*SubmitScoreResponse) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{3}
}

type GetScoresRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index         uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Amount        uint32 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	MyAnonymousId uint32 `protobuf:"varint,3,opt,name=my_anonymous_id,json=myAnonymousId,proto3" json:"my_anonymous_id,omitempty"`
	BoardName     string `protobuf:"bytes,4,opt,name=boardName,proto3" json:"boardName,omitempty"`
}

func (x *GetScoresRequest) Reset() {
	*x = GetScoresRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoresRequest) ProtoMessage() {}

func (x *GetScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoresRequest.ProtoReflect.Descriptor instead.
func (*GetScoresRequest) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{4}
}

func (x *GetScoresRequest) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GetScoresRequest) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetScoresRequest) GetMyAnonymousId() uint32 {
	if x != nil {
		return x.MyAnonymousId
	}
	return 0
}

func (x *GetScoresRequest) GetBoardName() string {
	if x != nil {
		return x.BoardName
	}
	return ""
}

type GetScoresResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scores      map[int32]*GetScoresResponse_Score `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TotalScores int32                              `protobuf:"varint,2,opt,name=total_scores,json=totalScores,proto3" json:"total_scores,omitempty"`
	YourScore   *int32                             `protobuf:"varint,4,opt,name=your_score,json=yourScore,proto3,oneof" json:"your_score,omitempty"`
}

func (x *GetScoresResponse) Reset() {
	*x = GetScoresResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoresResponse) ProtoMessage() {}

func (x *GetScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoresResponse.ProtoReflect.Descriptor instead.
func (*GetScoresResponse) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{5}
}

func (x *GetScoresResponse) GetScores() map[int32]*GetScoresResponse_Score {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *GetScoresResponse) GetTotalScores() int32 {
	if x != nil {
		return x.TotalScores
	}
	return 0
}

func (x *GetScoresResponse) GetYourScore() int32 {
	if x != nil && x.YourScore != nil {
		return *x.YourScore
	}
	return 0
}

type WordsForBoardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Board []byte `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
}

func (x *WordsForBoardRequest) Reset() {
	*x = WordsForBoardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordsForBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordsForBoardRequest) ProtoMessage() {}

func (x *WordsForBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordsForBoardRequest.ProtoReflect.Descriptor instead.
func (*WordsForBoardRequest) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{6}
}

func (x *WordsForBoardRequest) GetBoard() []byte {
	if x != nil {
		return x.Board
	}
	return nil
}

type WordsForBoardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Board []byte `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
}

func (x *WordsForBoardResponse) Reset() {
	*x = WordsForBoardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordsForBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordsForBoardResponse) ProtoMessage() {}

func (x *WordsForBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordsForBoardResponse.ProtoReflect.Descriptor instead.
func (*WordsForBoardResponse) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{7}
}

func (x *WordsForBoardResponse) GetBoard() []byte {
	if x != nil {
		return x.Board
	}
	return nil
}

type SeedBoardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeedWord string `protobuf:"bytes,1,opt,name=seed_word,json=seedWord,proto3" json:"seed_word,omitempty"`
	Width    int32  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height   int32  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Attempts int32  `protobuf:"varint,4,opt,name=attempts,proto3" json:"attempts,omitempty"`
}

func (x *SeedBoardRequest) Reset() {
	*x = SeedBoardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeedBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedBoardRequest) ProtoMessage() {}

func (x *SeedBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedBoardRequest.ProtoReflect.Descriptor instead.
func (*SeedBoardRequest) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{8}
}

func (x *SeedBoardRequest) GetSeedWord() string {
	if x != nil {
		return x.SeedWord
	}
	return ""
}

func (x *SeedBoardRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *SeedBoardRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *SeedBoardRequest) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

type SeedBoardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Board    []byte `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	Attempts int32  `protobuf:"varint,2,opt,name=attempts,proto3" json:"attempts,omitempty"`
	Progress int32  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
}

func (x *SeedBoardResponse) Reset() {
	*x = SeedBoardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeedBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedBoardResponse) ProtoMessage() {}

func (x *SeedBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedBoardResponse.ProtoReflect.Descriptor instead.
func (*SeedBoardResponse) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{9}
}

func (x *SeedBoardResponse) GetBoard() []byte {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *SeedBoardResponse) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *SeedBoardResponse) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type FillInBoardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Board    []byte `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	Attempts int32  `protobuf:"varint,2,opt,name=attempts,proto3" json:"attempts,omitempty"`
}

func (x *FillInBoardRequest) Reset() {
	*x = FillInBoardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FillInBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillInBoardRequest) ProtoMessage() {}

func (x *FillInBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillInBoardRequest.ProtoReflect.Descriptor instead.
func (*FillInBoardRequest) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{10}
}

func (x *FillInBoardRequest) GetBoard() []byte {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *FillInBoardRequest) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

type FillInBoardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Board    []byte `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	Attempts int32  `protobuf:"varint,2,opt,name=attempts,proto3" json:"attempts,omitempty"`
	Progress int32  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
}

func (x *FillInBoardResponse) Reset() {
	*x = FillInBoardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FillInBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillInBoardResponse) ProtoMessage() {}

func (x *FillInBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillInBoardResponse.ProtoReflect.Descriptor instead.
func (*FillInBoardResponse) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{11}
}

func (x *FillInBoardResponse) GetBoard() []byte {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *FillInBoardResponse) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *FillInBoardResponse) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type CreateTeamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateTeamRequest) Reset() {
	*x = CreateTeamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRequest) ProtoMessage() {}

func (x *CreateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamRequest) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{12}
}

func (x *CreateTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type JoinTeamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *JoinTeamRequest) Reset() {
	*x = JoinTeamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTeamRequest) ProtoMessage() {}

func (x *JoinTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTeamRequest.ProtoReflect.Descriptor instead.
func (*JoinTeamRequest) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{13}
}

func (x *JoinTeamRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JoinTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChangeNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ChangeNameRequest) Reset() {
	*x = ChangeNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeNameRequest) ProtoMessage() {}

func (x *ChangeNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeNameRequest.ProtoReflect.Descriptor instead.
func (*ChangeNameRequest) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{14}
}

func (x *ChangeNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WordGuessedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *WordGuessedRequest) Reset() {
	*x = WordGuessedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordGuessedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordGuessedRequest) ProtoMessage() {}

func (x *WordGuessedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordGuessedRequest.ProtoReflect.Descriptor instead.
func (*WordGuessedRequest) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{15}
}

func (x *WordGuessedRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type TeamStreamClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//	*TeamStreamClientMessage_Create
	//	*TeamStreamClientMessage_Join
	//	*TeamStreamClientMessage_Name
	//	*TeamStreamClientMessage_Word
	Request isTeamStreamClientMessage_Request `protobuf_oneof:"request"`
}

func (x *TeamStreamClientMessage) Reset() {
	*x = TeamStreamClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamStreamClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamStreamClientMessage) ProtoMessage() {}

func (x *TeamStreamClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamStreamClientMessage.ProtoReflect.Descriptor instead.
func (*TeamStreamClientMessage) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{16}
}

func (m *TeamStreamClientMessage) GetRequest() isTeamStreamClientMessage_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *TeamStreamClientMessage) GetCreate() *CreateTeamRequest {
	if x, ok := x.GetRequest().(*TeamStreamClientMessage_Create); ok {
		return x.Create
	}
	return nil
}

func (x *TeamStreamClientMessage) GetJoin() *JoinTeamRequest {
	if x, ok := x.GetRequest().(*TeamStreamClientMessage_Join); ok {
		return x.Join
	}
	return nil
}

func (x *TeamStreamClientMessage) GetName() *ChangeNameRequest {
	if x, ok := x.GetRequest().(*TeamStreamClientMessage_Name); ok {
		return x.Name
	}
	return nil
}

func (x *TeamStreamClientMessage) GetWord() *WordGuessedRequest {
	if x, ok := x.GetRequest().(*TeamStreamClientMessage_Word); ok {
		return x.Word
	}
	return nil
}

type isTeamStreamClientMessage_Request interface {
	isTeamStreamClientMessage_Request()
}

type TeamStreamClientMessage_Create struct {
	// The stream must start with one create or join message. After this, the
	// server responds with TeamInfoResponse, after which the create or join
	// must not be sent anymore. If the player name already exists in the team,
	// the server will respond with an ErrorResponse and the stream will be
	// closed.
	Create *CreateTeamRequest `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type TeamStreamClientMessage_Join struct {
	Join *JoinTeamRequest `protobuf:"bytes,2,opt,name=join,proto3,oneof"`
}

type TeamStreamClientMessage_Name struct {
	// When the player changes their name, send a ChangeNameRequest; the
	// server will respond with a new TeamInfoResponse to everyone. If the
	// name is already in use, the server will respond with an ErrorResponse
	// and the name will not be changed.
	Name *ChangeNameRequest `protobuf:"bytes,3,opt,name=name,proto3,oneof"`
}

type TeamStreamClientMessage_Word struct {
	// When the player guesses a word, send this request; the server will
	// send a WordGuessedResponse to all other players.
	Word *WordGuessedRequest `protobuf:"bytes,4,opt,name=word,proto3,oneof"`
}

func (*TeamStreamClientMessage_Create) isTeamStreamClientMessage_Request() {}

func (*TeamStreamClientMessage_Join) isTeamStreamClientMessage_Request() {}

func (*TeamStreamClientMessage_Name) isTeamStreamClientMessage_Request() {}

func (*TeamStreamClientMessage_Word) isTeamStreamClientMessage_Request() {}

type ErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{17}
}

func (x *ErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TeamInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	YourName string   `protobuf:"bytes,2,opt,name=your_name,json=yourName,proto3" json:"your_name,omitempty"`
	Players  []string `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *TeamInfoResponse) Reset() {
	*x = TeamInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamInfoResponse) ProtoMessage() {}

func (x *TeamInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamInfoResponse.ProtoReflect.Descriptor instead.
func (*TeamInfoResponse) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{18}
}

func (x *TeamInfoResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TeamInfoResponse) GetYourName() string {
	if x != nil {
		return x.YourName
	}
	return ""
}

func (x *TeamInfoResponse) GetPlayers() []string {
	if x != nil {
		return x.Players
	}
	return nil
}

type WordGuessedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player string `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Word   string `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *WordGuessedResponse) Reset() {
	*x = WordGuessedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordGuessedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordGuessedResponse) ProtoMessage() {}

func (x *WordGuessedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordGuessedResponse.ProtoReflect.Descriptor instead.
func (*WordGuessedResponse) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{19}
}

func (x *WordGuessedResponse) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

func (x *WordGuessedResponse) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type TeamStreamServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*TeamStreamServerMessage_Error
	//	*TeamStreamServerMessage_Team
	//	*TeamStreamServerMessage_Word
	Response isTeamStreamServerMessage_Response `protobuf_oneof:"response"`
}

func (x *TeamStreamServerMessage) Reset() {
	*x = TeamStreamServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamStreamServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamStreamServerMessage) ProtoMessage() {}

func (x *TeamStreamServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamStreamServerMessage.ProtoReflect.Descriptor instead.
func (*TeamStreamServerMessage) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{20}
}

func (m *TeamStreamServerMessage) GetResponse() isTeamStreamServerMessage_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *TeamStreamServerMessage) GetError() *ErrorResponse {
	if x, ok := x.GetResponse().(*TeamStreamServerMessage_Error); ok {
		return x.Error
	}
	return nil
}

func (x *TeamStreamServerMessage) GetTeam() *TeamInfoResponse {
	if x, ok := x.GetResponse().(*TeamStreamServerMessage_Team); ok {
		return x.Team
	}
	return nil
}

func (x *TeamStreamServerMessage) GetWord() *WordGuessedResponse {
	if x, ok := x.GetResponse().(*TeamStreamServerMessage_Word); ok {
		return x.Word
	}
	return nil
}

type isTeamStreamServerMessage_Response interface {
	isTeamStreamServerMessage_Response()
}

type TeamStreamServerMessage_Error struct {
	Error *ErrorResponse `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type TeamStreamServerMessage_Team struct {
	Team *TeamInfoResponse `protobuf:"bytes,2,opt,name=team,proto3,oneof"`
}

type TeamStreamServerMessage_Word struct {
	Word *WordGuessedResponse `protobuf:"bytes,3,opt,name=word,proto3,oneof"`
}

func (*TeamStreamServerMessage_Error) isTeamStreamServerMessage_Response() {}

func (*TeamStreamServerMessage_Team) isTeamStreamServerMessage_Response() {}

func (*TeamStreamServerMessage_Word) isTeamStreamServerMessage_Response() {}

type GetScoresResponse_Score struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TeamSize int32  `protobuf:"varint,2,opt,name=team_size,json=teamSize,proto3" json:"team_size,omitempty"`
	Words    int32  `protobuf:"varint,3,opt,name=words,proto3" json:"words,omitempty"`
	Seconds  int32  `protobuf:"varint,4,opt,name=seconds,proto3" json:"seconds,omitempty"`
}

func (x *GetScoresResponse_Score) Reset() {
	*x = GetScoresResponse_Score{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vierkantle_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScoresResponse_Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoresResponse_Score) ProtoMessage() {}

func (x *GetScoresResponse_Score) ProtoReflect() protoreflect.Message {
	mi := &file_vierkantle_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoresResponse_Score.ProtoReflect.Descriptor instead.
func (*GetScoresResponse_Score) Descriptor() ([]byte, []int) {
	return file_vierkantle_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetScoresResponse_Score) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetScoresResponse_Score) GetTeamSize() int32 {
	if x != nil {
		return x.TeamSize
	}
	return 0
}

func (x *GetScoresResponse_Score) GetWords() int32 {
	if x != nil {
		return x.Words
	}
	return 0
}

func (x *GetScoresResponse_Score) GetSeconds() int32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

var File_vierkantle_proto protoreflect.FileDescriptor

var file_vierkantle_proto_rawDesc = []byte{
	0x0a, 0x10, 0x76, 0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e, 0x74, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0d, 0x6e, 0x6c, 0x2e, 0x76, 0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e, 0x74, 0x6c,
	0x65, 0x22, 0x47, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x15, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65,
	0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x15, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x4f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xa2, 0x01, 0x0a, 0x12, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x77, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x15, 0x0a,
	0x13, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x6d, 0x79, 0x5f, 0x61, 0x6e,
	0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0d, 0x6d, 0x79, 0x41, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xfc, 0x02,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6e, 0x6c, 0x2e, 0x76, 0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e,
	0x74, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0a,
	0x79, 0x6f, 0x75, 0x72, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x00, 0x52, 0x09, 0x79, 0x6f, 0x75, 0x72, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x88, 0x01, 0x01,
	0x1a, 0x68, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x6f,
	0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x1a, 0x61, 0x0a, 0x0b, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x3c, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6e, 0x6c, 0x2e,
	0x76, 0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e, 0x74, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x0d, 0x0a,
	0x0b, 0x5f, 0x79, 0x6f, 0x75, 0x72, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x2c, 0x0a, 0x14,
	0x57, 0x6f, 0x72, 0x64, 0x73, 0x46, 0x6f, 0x72, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x22, 0x2d, 0x0a, 0x15, 0x57, 0x6f,
	0x72, 0x64, 0x73, 0x46, 0x6f, 0x72, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x22, 0x79, 0x0a, 0x10, 0x53, 0x65, 0x65,
	0x64, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x65, 0x65, 0x64, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x65, 0x65, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x74, 0x74, 0x65,
	0x6d, 0x70, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x74, 0x74, 0x65,
	0x6d, 0x70, 0x74, 0x73, 0x22, 0x61, 0x0a, 0x11, 0x53, 0x65, 0x65, 0x64, 0x42, 0x6f, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x61,
	0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70,
	0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x22, 0x46, 0x0a, 0x12, 0x46, 0x69, 0x6c, 0x6c, 0x49,
	0x6e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73, 0x22,
	0x63, 0x0a, 0x13, 0x46, 0x69, 0x6c, 0x6c, 0x49, 0x6e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x22, 0x27, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3b, 0x0a,
	0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x11, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x28, 0x0a, 0x12, 0x57, 0x6f, 0x72, 0x64, 0x47, 0x75, 0x65, 0x73, 0x73,
	0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x87, 0x02,
	0x0a, 0x17, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x06, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6e, 0x6c, 0x2e, 0x76,
	0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e, 0x74, 0x6c, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x34, 0x0a, 0x04, 0x6a, 0x6f, 0x69, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6e, 0x6c, 0x2e, 0x76, 0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e,
	0x74, 0x6c, 0x65, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x04, 0x6a, 0x6f, 0x69, 0x6e, 0x12, 0x36, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6e, 0x6c, 0x2e, 0x76,
	0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e, 0x74, 0x6c, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x37, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x6e, 0x6c, 0x2e, 0x76, 0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e, 0x74, 0x6c,
	0x65, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x47, 0x75, 0x65, 0x73, 0x73, 0x65, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x42, 0x09, 0x0a, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x25, 0x0a, 0x0d, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x5f,
	0x0a, 0x10, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x79, 0x6f, 0x75, 0x72,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x79, 0x6f, 0x75,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22,
	0x41, 0x0a, 0x13, 0x57, 0x6f, 0x72, 0x64, 0x47, 0x75, 0x65, 0x73, 0x73, 0x65, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f,
	0x72, 0x64, 0x22, 0xcc, 0x01, 0x0a, 0x17, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x34,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x6e, 0x6c, 0x2e, 0x76, 0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e, 0x74, 0x6c, 0x65, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x35, 0x0a, 0x04, 0x74, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6e, 0x6c, 0x2e, 0x76, 0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e, 0x74,
	0x6c, 0x65, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x61, 0x6d, 0x12, 0x38, 0x0a, 0x04, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6e, 0x6c, 0x2e, 0x76,
	0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e, 0x74, 0x6c, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x47, 0x75,
	0x65, 0x73, 0x73, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x04, 0x77, 0x6f, 0x72, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0xfc, 0x04, 0x0a, 0x11, 0x56, 0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e, 0x74, 0x6c, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x42, 0x6f,
	0x61, 0x72, 0x64, 0x12, 0x1e, 0x2e, 0x6e, 0x6c, 0x2e, 0x76, 0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e,
	0x74, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6e, 0x6c, 0x2e, 0x76, 0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e,
	0x74, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x21, 0x2e, 0x6e, 0x6c, 0x2e, 0x76, 0x69, 0x65, 0x72, 0x6b,
	0x61, 0x6e, 0x74, 0x6c, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6e, 0x6c, 0x2e, 0x76, 0x69,
	0x65, 0x72, 0x6b, 0x61, 0x6e, 0x74, 0x6c, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50,
	0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x6e, 0x6c,
	0x2e, 0x76, 0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e, 0x74, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6e,
	0x6c, 0x2e, 0x76, 0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e, 0x74, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x5c, 0x0a, 0x0d, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x46, 0x6f, 0x72, 0x42, 0x6f, 0x61, 0x72,
	0x64, 0x12, 0x23, 0x2e, 0x6e, 0x6c, 0x2e, 0x76, 0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e, 0x74, 0x6c,
	0x65, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x46, 0x6f, 0x72, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6e, 0x6c, 0x2e, 0x76, 0x69, 0x65, 0x72,
	0x6b, 0x61, 0x6e, 0x74, 0x6c, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x46, 0x6f, 0x72, 0x42,
	0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52,
	0x0a, 0x09, 0x53, 0x65, 0x65, 0x64, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x1f, 0x2e, 0x6e, 0x6c,
	0x2e, 0x76, 0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e, 0x74, 0x6c, 0x65, 0x2e, 0x53, 0x65, 0x65, 0x64,
	0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6e,
	0x6c, 0x2e, 0x76, 0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e, 0x74, 0x6c, 0x65, 0x2e, 0x53, 0x65, 0x65,
	0x64, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x30, 0x01, 0x12, 0x58, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x6c, 0x49, 0x6e, 0x42, 0x6f, 0x61, 0x72,
	0x64, 0x12, 0x21, 0x2e, 0x6e, 0x6c, 0x2e, 0x76, 0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e, 0x74, 0x6c,
	0x65, 0x2e, 0x46, 0x69, 0x6c, 0x6c, 0x49, 0x6e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6e, 0x6c, 0x2e, 0x76, 0x69, 0x65, 0x72, 0x6b, 0x61,
	0x6e, 0x74, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x6c, 0x49, 0x6e, 0x42, 0x6f, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x62, 0x0a, 0x0a,
	0x54, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x26, 0x2e, 0x6e, 0x6c, 0x2e,
	0x76, 0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e, 0x74, 0x6c, 0x65, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x1a, 0x26, 0x2e, 0x6e, 0x6c, 0x2e, 0x76, 0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e, 0x74,
	0x6c, 0x65, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73,
	0x67, 0x69, 0x65, 0x6c, 0x65, 0x6e, 0x2f, 0x76, 0x69, 0x65, 0x72, 0x6b, 0x61, 0x6e, 0x74, 0x6c,
	0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_vierkantle_proto_rawDescOnce sync.Once
	file_vierkantle_proto_rawDescData = file_vierkantle_proto_rawDesc
)

func file_vierkantle_proto_rawDescGZIP() []byte {
	file_vierkantle_proto_rawDescOnce.Do(func() {
		file_vierkantle_proto_rawDescData = protoimpl.X.CompressGZIP(file_vierkantle_proto_rawDescData)
	})
	return file_vierkantle_proto_rawDescData
}

var file_vierkantle_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_vierkantle_proto_goTypes = []interface{}{
	(*GetBoardRequest)(nil),         // 0: nl.vierkantle.GetBoardRequest
	(*GetBoardResponse)(nil),        // 1: nl.vierkantle.GetBoardResponse
	(*SubmitScoreRequest)(nil),      // 2: nl.vierkantle.SubmitScoreRequest
	(*SubmitScoreResponse)(nil),     // 3: nl.vierkantle.SubmitScoreResponse
	(*GetScoresRequest)(nil),        // 4: nl.vierkantle.GetScoresRequest
	(*GetScoresResponse)(nil),       // 5: nl.vierkantle.GetScoresResponse
	(*WordsForBoardRequest)(nil),    // 6: nl.vierkantle.WordsForBoardRequest
	(*WordsForBoardResponse)(nil),   // 7: nl.vierkantle.WordsForBoardResponse
	(*SeedBoardRequest)(nil),        // 8: nl.vierkantle.SeedBoardRequest
	(*SeedBoardResponse)(nil),       // 9: nl.vierkantle.SeedBoardResponse
	(*FillInBoardRequest)(nil),      // 10: nl.vierkantle.FillInBoardRequest
	(*FillInBoardResponse)(nil),     // 11: nl.vierkantle.FillInBoardResponse
	(*CreateTeamRequest)(nil),       // 12: nl.vierkantle.CreateTeamRequest
	(*JoinTeamRequest)(nil),         // 13: nl.vierkantle.JoinTeamRequest
	(*ChangeNameRequest)(nil),       // 14: nl.vierkantle.ChangeNameRequest
	(*WordGuessedRequest)(nil),      // 15: nl.vierkantle.WordGuessedRequest
	(*TeamStreamClientMessage)(nil), // 16: nl.vierkantle.TeamStreamClientMessage
	(*ErrorResponse)(nil),           // 17: nl.vierkantle.ErrorResponse
	(*TeamInfoResponse)(nil),        // 18: nl.vierkantle.TeamInfoResponse
	(*WordGuessedResponse)(nil),     // 19: nl.vierkantle.WordGuessedResponse
	(*TeamStreamServerMessage)(nil), // 20: nl.vierkantle.TeamStreamServerMessage
	(*GetScoresResponse_Score)(nil), // 21: nl.vierkantle.GetScoresResponse.Score
	nil,                             // 22: nl.vierkantle.GetScoresResponse.ScoresEntry
}
var file_vierkantle_proto_depIdxs = []int32{
	22, // 0: nl.vierkantle.GetScoresResponse.scores:type_name -> nl.vierkantle.GetScoresResponse.ScoresEntry
	12, // 1: nl.vierkantle.TeamStreamClientMessage.create:type_name -> nl.vierkantle.CreateTeamRequest
	13, // 2: nl.vierkantle.TeamStreamClientMessage.join:type_name -> nl.vierkantle.JoinTeamRequest
	14, // 3: nl.vierkantle.TeamStreamClientMessage.name:type_name -> nl.vierkantle.ChangeNameRequest
	15, // 4: nl.vierkantle.TeamStreamClientMessage.word:type_name -> nl.vierkantle.WordGuessedRequest
	17, // 5: nl.vierkantle.TeamStreamServerMessage.error:type_name -> nl.vierkantle.ErrorResponse
	18, // 6: nl.vierkantle.TeamStreamServerMessage.team:type_name -> nl.vierkantle.TeamInfoResponse
	19, // 7: nl.vierkantle.TeamStreamServerMessage.word:type_name -> nl.vierkantle.WordGuessedResponse
	21, // 8: nl.vierkantle.GetScoresResponse.ScoresEntry.value:type_name -> nl.vierkantle.GetScoresResponse.Score
	0,  // 9: nl.vierkantle.VierkantleService.GetBoard:input_type -> nl.vierkantle.GetBoardRequest
	2,  // 10: nl.vierkantle.VierkantleService.SubmitScore:input_type -> nl.vierkantle.SubmitScoreRequest
	4,  // 11: nl.vierkantle.VierkantleService.GetScores:input_type -> nl.vierkantle.GetScoresRequest
	6,  // 12: nl.vierkantle.VierkantleService.WordsForBoard:input_type -> nl.vierkantle.WordsForBoardRequest
	8,  // 13: nl.vierkantle.VierkantleService.SeedBoard:input_type -> nl.vierkantle.SeedBoardRequest
	10, // 14: nl.vierkantle.VierkantleService.FillInBoard:input_type -> nl.vierkantle.FillInBoardRequest
	16, // 15: nl.vierkantle.VierkantleService.TeamStream:input_type -> nl.vierkantle.TeamStreamClientMessage
	1,  // 16: nl.vierkantle.VierkantleService.GetBoard:output_type -> nl.vierkantle.GetBoardResponse
	3,  // 17: nl.vierkantle.VierkantleService.SubmitScore:output_type -> nl.vierkantle.SubmitScoreResponse
	5,  // 18: nl.vierkantle.VierkantleService.GetScores:output_type -> nl.vierkantle.GetScoresResponse
	7,  // 19: nl.vierkantle.VierkantleService.WordsForBoard:output_type -> nl.vierkantle.WordsForBoardResponse
	9,  // 20: nl.vierkantle.VierkantleService.SeedBoard:output_type -> nl.vierkantle.SeedBoardResponse
	11, // 21: nl.vierkantle.VierkantleService.FillInBoard:output_type -> nl.vierkantle.FillInBoardResponse
	20, // 22: nl.vierkantle.VierkantleService.TeamStream:output_type -> nl.vierkantle.TeamStreamServerMessage
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_vierkantle_proto_init() }
func file_vierkantle_proto_init() {
	if File_vierkantle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vierkantle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBoardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vierkantle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBoardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vierkantle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitScoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vierkantle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitScoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vierkantle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScoresRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vierkantle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScoresResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vierkantle_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordsForBoardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vierkantle_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordsForBoardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vierkantle_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeedBoardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vierkantle_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeedBoardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vierkantle_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FillInBoardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vierkantle_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FillInBoardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vierkantle_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTeamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vierkantle_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinTeamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vierkantle_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vierkantle_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordGuessedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vierkantle_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamStreamClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vierkantle_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vierkantle_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vierkantle_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordGuessedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vierkantle_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamStreamServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vierkantle_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScoresResponse_Score); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_vierkantle_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_vierkantle_proto_msgTypes[16].OneofWrappers = []interface{}{
		(*TeamStreamClientMessage_Create)(nil),
		(*TeamStreamClientMessage_Join)(nil),
		(*TeamStreamClientMessage_Name)(nil),
		(*TeamStreamClientMessage_Word)(nil),
	}
	file_vierkantle_proto_msgTypes[20].OneofWrappers = []interface{}{
		(*TeamStreamServerMessage_Error)(nil),
		(*TeamStreamServerMessage_Team)(nil),
		(*TeamStreamServerMessage_Word)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vierkantle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vierkantle_proto_goTypes,
		DependencyIndexes: file_vierkantle_proto_depIdxs,
		MessageInfos:      file_vierkantle_proto_msgTypes,
	}.Build()
	File_vierkantle_proto = out.File
	file_vierkantle_proto_rawDesc = nil
	file_vierkantle_proto_goTypes = nil
	file_vierkantle_proto_depIdxs = nil
}
